### ISSUE TITLE
Error when I run the script

### ISSUE THREAD

**Issue by tXambe** [threatexpress/domainhunter#32]
Hello,

When I run the script ```python3 ./domainhunter.py -s mydomain.com``` I have this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fa77e2d0c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gitlab.com', port=443): Max retries exceeded with url: /gerowen/old-malware-domains-ad-list/-/raw/master/malwaredomainslist.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa77e2d0c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/PNTST/RECON/Domain-Expirated/domainhunter/./domainhunter.py", line 537, in <module>
    maldomains = downloadMalwareDomains(malwaredomainsURL)
  File "/opt/PNTST/RECON/Domain-Expirated/domainhunter/./domainhunter.py", line 294, in downloadMalwareDomains
    response = s.get(url=url,headers=headers,verify=False,proxies=proxies)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gitlab.com', port=443): Max retries exceeded with url: /gerowen/old-malware-domains-ad-list/-/raw/master/malwaredomainslist.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa77e2d0c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))


```
Anyone can help me ?

A greeting and thanks

**Comment by andrewchiles** [comment]
It looks like you're having an issue with DNS name resolution. I'd check to make sure you can resolve and connect to gitlab.com as the code is doing here:
>requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gitlab.com', port=443): Max retries exceeded with url: /gerowen/old-malware-domains-ad-list/-/raw/master/malwaredomainslist.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa77e2d0c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
